//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPDetail
    {
        public int ID { get; set; }
        public string GPCode { get; set; }
        public string GPSurname { get; set; }
        public string GPInitials { get; set; }
        public string GPPhone { get; set; }
    }
}
