//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string PassNumber { get; set; }
        public string ForeNames { get; set; }
        public string SurName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string HomeTelephoneNumber { get; set; }
        public int GeneralPartitioner { get; set; }
        public string NOKName { get; set; }
        public string relationShip { get; set; }
        public string NOKAddress1 { get; set; }
        public string NOKAddress2 { get; set; }
        public string NOKAddress3 { get; set; }
        public string NOKAddress4 { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public string GPSurName { get; set; }
    }
}
